name: health-privacy-env
channels:
  - bioconda
  - conda-forge
  - nvidia
  - pytorch

dependencies:
  - python=3.10
  - pytorch=2.2.0
  #- pytorch-cuda=12.1
  - numpy=1.26.4
  - pandas=2.2.3
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - pip=24.3.1
  - ipykernel=6.29.2
  - matplotlib==3.8.3
  - pyarrow==15.0.0
  - black==24.2.0
  - progress
  - seaborn
  - mkl-service
  - nbconvert

  - pip:
      - attrs
      - opacus==0.15.0
      #- torch==2.2.0
      - ctgan
      - domias
      - matplotlib
      - plotnine
      - opacus
      - tqdm
      - click
    #  - nvidia-cublas-cu12
      - PyYAML
      - statsmodels